apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hard-status-ingress
  labels:
    app: hard-status
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  rules:
  - host: {{ .Values.ingressHostname }}
    http:
      paths:
      - backend:
          serviceName: hard-status-service
          servicePort: 3001
