apiVersion: v1
kind: Service
metadata:
  name: hard-status-service
  labels:
    app: hard-status
spec:
  type: {{ .Values.serviceType }}
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: hard-status
